### ISSUE TITLE
不太清楚怎么拿到签名

### ISSUE THREAD

**Issue by chengfeng126** [ucloud/ufile-sdk-android#3]
您好，我下载了android   demo，不是太明白怎么签名的，有没有文档说明之类的，谢谢~

**Comment by voidzero42** [comment]
sign-generator  
http://testsign2.cn-sh2.ufileos.com/signGenerator.html

**Comment by JoshuaYin** [comment]
移动端使用建议使用远程签名服务，可以参考https://github.com/ucloud/ufile-sdk-auth-server
